import { ArrowLeft, MessageSquare, Download, Share, Sparkles, Cpu, Wifi } from "lucide-react";
import Link from "next/link";

export default function NoteEditor() {
  return (
    <div className="flex h-full w-full">
      
      {/* Main Document Area */}
      <div className="flex-1 overflow-y-auto p-8 md:p-12">
        <div className="mx-auto max-w-3xl">
          
          <Link href="/notes" className="mb-6 flex items-center gap-2 text-sm text-zinc-500 hover:text-zinc-300 transition-colors w-fit">
            <ArrowLeft size={16} />
            Back to Notes
          </Link>
          
          <div className="mb-8 flex items-end justify-between border-b border-white/10 pb-6">
            <div>
              <h1 className="text-4xl font-bold text-white tracking-tight">ESP32 & Microcontroller Pinouts</h1>
              <p className="mt-2 text-sm text-zinc-400">Generated by StudentOS AI • 2 days ago</p>
            </div>
            <div className="flex gap-3">
              <button className="flex items-center gap-2 rounded-lg bg-zinc-900 px-3 py-2 text-sm font-medium text-zinc-300 transition-colors hover:bg-zinc-800">
                <Share size={16} /> Share
              </button>
              <button className="flex items-center gap-2 rounded-lg bg-zinc-900 px-3 py-2 text-sm font-medium text-zinc-300 transition-colors hover:bg-zinc-800">
                <Download size={16} /> Export
              </button>
            </div>
          </div>

          {/* Document Content */}
          <div className="text-zinc-300">
            <p className="mb-6 leading-relaxed text-lg text-zinc-400">
              A comprehensive guide to understanding the ESP32 microcontroller, focusing on pin configurations, networking capabilities, and sensor integration.
            </p>

            <h2 className="text-2xl font-semibold text-white mb-4 mt-8 flex items-center gap-2">
              <Cpu size={24} className="text-cyan-500" />
              1. General Purpose Input/Output (GPIO)
            </h2>
            <p className="mb-4 leading-relaxed">
              The ESP32 features robust multiplexing, allowing multiple functions to be assigned to the same pins. When designing circuits (such as a Smart Attendance System), careful pin selection is required to avoid conflicts with strapping pins used during the boot process.
            </p>
            
            {/* AI Summary Highlight */}
            <div className="my-6 rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-4 border-l-2 border-l-cyan-500">
              <p className="text-sm text-cyan-200 flex gap-2 items-start">
                <Sparkles size={16} className="shrink-0 mt-0.5" />
                <span><strong>AI Tip:</strong> When connecting modules like the R307 fingerprint sensor or the RC522 RFID module, ensure you are utilizing the correct UART (TX/RX) and SPI hardware pins respectively to prevent data bottlenecking.</span>
              </p>
            </div>

            <h2 className="text-2xl font-semibold text-white mb-4 mt-8 flex items-center gap-2">
              <Wifi size={24} className="text-cyan-500" />
              2. Networking & Connectivity
            </h2>
            <p className="mb-4 leading-relaxed">
              Unlike the standard Arduino Uno, the ESP32 includes built-in Wi-Fi and Dual-mode Bluetooth. This makes it the ideal brain for IoT systems that require sending database logs (like LCD timestamps or user IDs) to a backend server in real-time.
            </p>
          </div>
        </div>
      </div>

      {/* Contextual AI Tutor Sidebar */}
      <div className="hidden w-80 shrink-0 flex-col border-l border-white/5 bg-zinc-950/30 xl:flex">
        
        <div className="p-4 border-b border-white/5 bg-zinc-900/20 flex items-center gap-2">
          <MessageSquare size={18} className="text-cyan-500" />
          <h3 className="font-medium text-white text-sm">Document Tutor</h3>
        </div>
        
        <div className="flex-1 overflow-y-auto p-4 flex flex-col gap-4">
          {/* Chat Bubble */}
          <div className="flex gap-3">
            <div className="h-8 w-8 shrink-0 rounded-full bg-cyan-900 flex items-center justify-center text-cyan-400">
              <Sparkles size={14} />
            </div>
            <div className="flex-1 rounded-2xl rounded-tl-sm bg-zinc-900 p-3 text-sm text-zinc-300 leading-relaxed">
              I have loaded your notes on the ESP32. Would you like me to generate a C++ code snippet for the RFID module, or draw a text-based circuit diagram for you?
            </div>
          </div>
        </div>

        {/* Chat Input */}
        <div className="p-4 border-t border-white/5 bg-zinc-900/20">
          <div className="relative flex items-center">
            <input 
              type="text" 
              placeholder="Ask about this document..." 
              className="w-full bg-zinc-900 border border-white/10 rounded-lg py-2.5 pl-3 pr-10 text-sm text-white placeholder-zinc-500 outline-none focus:border-cyan-500/50 transition-colors" 
            />
            <button className="absolute right-2 text-zinc-400 hover:text-cyan-400 transition-colors">
              <ArrowLeft size={16} className="rotate-180" />
            </button>
          </div>
        </div>

      </div>
    </div>
  );
}